sections:
  main:
    display: Main
    fields:
      -
        handle: terms
        field:
          collections:
            - pages
          display: Terms
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: privacy_policy
        field:
          collections:
            - pages
          display: 'Privacy Policy'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: login
        field:
          collections:
            - pages
          display: Login
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: forgot_password
        field:
          collections:
            - pages
          display: 'Forgot Password'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: set_password
        field:
          collections:
            - pages
          display: 'Set Password'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: register
        field:
          collections:
            - pages
          display: Register
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: register_group
        field:
          collections:
            - pages
          display: 'Register Group'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: experts
        field:
          collections:
            - pages
          display: Experts
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
